language: node_js
sudo: false

node_js:
  - '5'
  - '4'

after_script:
  npm run ci-coverage

cache:
  directories:
    - node_modules

addons:
  code_climate:
    repo_token: 891904e2b47fd678ce5baa404fba09299180c43fb73596d4706227ab143361a0
